# Generated by Django 3.1.6 on 2021-02-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210213_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prefPreferedMaxConsecutiveTime',
            new_name='PreferredMaxConsecutiveTime',
        ),
        migrations.RemoveField(
            model_name='fixedtask',
            name='fixedtaskID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
    ]
