# Generated by Django 3.1.6 on 2021-02-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210213_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedtask',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='userID',
            new_name='user',
        ),
    ]
