# Generated by Django 3.1.5 on 2021-02-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210213_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskLength',
            field=models.IntegerField(default=0),
        ),
    ]
